name: Releaser

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.19

      - name: Setup VS environment
        shell: cmd
        run: |
          for /f "usebackq delims=" %%i in (`vswhere.exe -latest -property installationPath`) do echo %%i\VC\Auxiliary\Build>>%GITHUB_PATH%

      - name: Build
        id: build
        shell: cmd
        run: |
          set GOPATH=%USERPROFILE%\go
          echo ::set-output name=version::%GITHUB_REF:~11%
          build.bat

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: ${{ steps.build.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GPR_TOKEN }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: bin/*-Setup.exe
